"""create_wallet_requests_table

Revision ID: 3b8a37030325
Revises: 
Create Date: 2025-03-05 11:50:10.348157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8a37030325'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('bandwidth', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('trx_balance', sa.Float(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_requests_address'), 'wallet_requests', ['address'], unique=False)
    op.create_index(op.f('ix_wallet_requests_id'), 'wallet_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_requests_id'), table_name='wallet_requests')
    op.drop_index(op.f('ix_wallet_requests_address'), table_name='wallet_requests')
    op.drop_table('wallet_requests')
    # ### end Alembic commands ###
